[tool.poetry]
name = "blocklistmetrics"
version = "0.1.0"
description = ""
authors = ["Armin Wasicek <armin.wasicek@avast.com>"]

[tool.poetry.dependencies]
python = ">=3.7"
requests = ">=2.27"
certifi = "^2022.6.15"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
